import React from "react";
import "./Style.css";
import myimg from "./img/logonew.png";
import myaudiobook from "./img/audiobook.png";

const Home = () => {
  return (
    <div>
      <section className="section-hero">
        <div className="hero">
          <div className="hero-text-box">
            <h1 className="heading-primary">
              Analyze any text with a click of a button
            </h1>
            <p className="hero-description">
              Text-o-matic can condense articles, papers, or documents down to
              the key points instantly. Our AI uses natural language processing
              to locate critical information while maintaining the original
              context.
            </p>

            <a href="#" className="btn btn--outline">
              Learn more ↓
            </a>
          </div>
          <div className="hero-img-box">
            <img
              src={myimg}
              className="hero-img img-fluid animate_animated animate_pulse"
              alt="intelligent text analyzer"
            />
          </div>
          {/* ////////////////////////////////////////////////// */}

          {/* <div id="features" className="col-row row">
            <h1>Features</h1>
          </div>
          <div className="col-md-8 d-flex align-items-center">
            <ul className="list-unstyled ui-steps">
              <li className="media" id={1}>
                <div id="icon-1" className="circle-icon mr-4">
                  1
                </div>
                <div className="media-body">
                  <h1>Summary Generation</h1>
                  <p>
                    The better version of your information will be generated by
                    extracting the most important parts of it.
                  </p>
                </div>
              </li>
              <li className="media" id={2}>
                <div id="icon-2" className="circle-icon mr-4">
                  2
                </div>
                <div className="media-body">
                  <h1>Sentiment analyzer</h1>
                  <p>Get .......</p>
                </div>
              </li>

              <li className="media" id={6}>
                <div id="icon-6" className="circle-icon mr-4">
                  3
                </div>
                <div className="media-body">
                  <h1>Save Your Results</h1>
                  <p>Download, save or share your summary for free.</p>
                </div>
              </li>
            </ul> */}
          {/* </div> */}
        </div>
      </section>

      {/* ////////////////////////////////////////////////////////////////////// */}

      <section>
        <div style={{ background: "#dff1ee" }}>
          <div className="container">
            <br />
            <p className="display-6  text-center "> Get started in minutes</p>
            <p className="display-4 text-center ">
              3 simple & easy step to launch.
            </p>
            <br />
            <br />
            <div className="row">
              <div className="col-sm-4">
                <div
                  className="card w-80 animate_animated animate_slideInUp "
                  style={{ background: "#dff1ee" }}
                >
                  <div className="card-body" style={{ transition: "1sec" }}>
                    <img
                      src="https://www.sammurize.com/images/assets/ils_15.svg"
                      alt=""
                      className="img-fluid  card-img-top "
                    />
                    <p>Join Our Platform</p>
                    <p className=" fw-bold">
                      It only takes a minute. <br /> Set up is smooth and simple
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-sm-4">
                <div
                  className="card w-80 animate_animated animate_slideInUp"
                  style={{ background: "#dff1ee" }}
                >
                  <div className="card-body">
                    <img
                      src="https://www.sammurize.com/images/assets/ils_16.svg"
                      alt=""
                      className="img-fluid  card-img-top"
                    />
                    <p>Create new research</p>
                    <p className=" fw-bold">
                      Create a new research and start gathering documents as pdf
                      files or public URL article links
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-sm-4">
                <div
                  className="card w-80 animate_animated animate_slideInUp"
                  style={{ background: "#dff1ee" }}
                >
                  <div className="card-body">
                    <img
                      src="https://www.sammurize.com/images/assets/ils_07.svg"
                      alt=" "
                      width="100"
                      className="img-fluid card-img-top"
                    />
                    <p>Start summarizing text</p>
                    <p className=" fw-bold">
                      Get detailed keywords and <br /> summarize main points{" "}
                      <br /> for each document
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* /////////////////////// */}

      <section>
        <div style={{ background: "#dff1ee" }}>
          <div className="container">
            <p className="display-4 text-center">Features</p>

            <div className="card" style={{ background: "#dff1ee" }}>
              <div className="card-body">
                <div className="row">
                  <div className="col-md-4">
                    <img
                      className="img-fluid"
                      src="https://play-lh.googleusercontent.com/UM9Ibkkqp304zSfGwTAWPyaM4-mUq5gc9EiNEtqS50dV-qblidxmx1I_eJZnEpAV77w=w600-h300-pc0xffffff-pd"
                      alt="Title"
                    />
                  </div>
                  <div className="col-md-8 d-flex flex-column justify-content-center">
                  {/* <div className="col-md-8"> */}
                    <p className="display-4 fw-bold">Summary Generation</p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                    Eos error sed beatae porro cumque voluptatum exercitationem
                    ea animi maiores officiis repellat facilis, excepturi,
                    temporibus ad quae? Praesentium, inventore earum obcaecati
                    fugit architecto ipsum vel pariatur nulla ex veritatis
                    temporibus esse quisquam quos nostrum ratione totam
                    doloribus, eligendi ducimus illo aliquid?
                  </div>
                </div>
              </div>
            </div>
            <div className="card mt-4 " style={{ background: "#dff1ee" }}>
              <div className="card-body">
                <div className="row">
                  {/* <div className="col-md-8 d-flex flex-column justify-content-center"> */}
                  <div className="col-md-8 d-flex flex-column justify-content-center">
                    <p className="display-4 fw-bold">Sentiment Analysis</p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                    Eos error sed beatae porro cumque voluptatum exercitationem
                    ea animi maiores officiis repellat facilis, excepturi,
                    temporibus ad quae? Praesentium, inventore earum obcaecati
                    fugit architecto ipsum vel pariatur nulla ex veritatis
                    temporibus esse quisquam quos nostrum ratione totam
                    doloribus, eligendi ducimus illo aliquid?
                  </div>
                  <div className="col-md-4">
                    <img
                      className="img-fluid"
                      src="https://yellow.ai/wp-content/uploads/2022/01/customer-sentiment-analysis.svg"
                      alt="Title"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="card mt-4" style={{ background: "#dff1ee" }}>
              <div className="card-body">
                <div className="row">
                  <div className="col-md-4">
                    <img
                      className="img-fluid"
                      src={myaudiobook}
                      alt="Title"
                    />
                  </div>
                  <div className="col-md-8 d-flex flex-column justify-content-center">
                  {/* <div className="col-md-8"> */}
                    <p className="display-4 fw-bold">Text To Audio</p>
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                    Eos error sed beatae porro cumque voluptatum exercitationem
                    ea animi maiores officiis repellat facilis, excepturi,
                    temporibus ad quae? Praesentium, inventore earum obcaecati
                    fugit architecto ipsum vel pariatur nulla ex veritatis
                    temporibus esse quisquam quos nostrum ratione totam
                    doloribus, eligendi ducimus illo aliquid?
                  </div>
                </div>
              </div>
            </div>

            <>
              {/* <section class="light">
                <div class="container py-2">
                  <div
                    class="h1 text-center text-dark"
                    id="pageHeaderTitle"
                  ></div>

                  <article class="postcard light red">
                    <a class="postcard__img_link" href="#"></a>
                    <div class="postcard__text t-dark">
                      <h1 class="postcard__title red">
                        <a href="#">Summary Generation</a>
                      </h1>
                      <div class="postcard__subtitle small"></div>
                      <div class="postcard__bar"></div>
                      <div class="postcard__preview-txt">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Eligendi, fugiat asperiores inventore beatae accusamus
                        odit minima enim, commodi quia, doloribus eius! Ducimus
                        nemo accusantium maiores velit corrupti tempora
                        reiciendis molestiae repellat vero. Eveniet ipsam
                        adipisci illo iusto quibusdam, sunt neque nulla unde
                        ipsum dolores nobis enim quidem excepturi, illum quos!
                      </div>
                    </div>
                  </article>
                  <article class="postcard light green">
                    <a class="postcard__img_link" href="#">
                      <img
                        class="postcard__img"
                        src="https://picsum.photos/500/501"
                        alt="Image Title"
                      />
                    </a>
                    <div class="postcard__text t-dark">
                      <h1 class="postcard__title green">
                        <a href="#">Sentiment Analysis</a>
                      </h1>
                      <div class="postcard__subtitle small"></div>
                      <div class="postcard__bar"></div>
                      <div class="postcard__preview-txt">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Eligendi, fugiat asperiores inventore beatae accusamus
                        odit minima enim, commodi quia, doloribus eius! Ducimus
                        nemo accusantium maiores velit corrupti tempora
                        reiciendis molestiae repellat vero. Eveniet ipsam
                        adipisci illo iusto quibusdam, sunt neque nulla unde
                        ipsum dolores nobis enim quidem excepturi, illum quos!
                      </div>
                    </div>
                  </article>
                  <article class="postcard light yellow">
                    <a class="postcard__img_link" href="#">
                      <img
                        class="postcard__img"
                        src="https://picsum.photos/501/501"
                        alt="Image Title"
                      />
                    </a>
                    <div class="postcard__text t-dark">
                      <h1 class="postcard__title yellow">
                        <a href="#">Text to Audio</a>
                      </h1>
                      <div class="postcard__subtitle small"></div>
                      <div class="postcard__bar"></div>
                      <div class="postcard__preview-txt">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Eligendi, fugiat asperiores inventore beatae accusamus
                        odit minima enim, commodi quia, doloribus eius! Ducimus
                        nemo accusantium maiores velit corrupti tempora
                        reiciendis molestiae repellat vero. Eveniet ipsam
                        adipisci illo iusto quibusdam, sunt neque nulla unde
                        ipsum dolores nobis enim quidem excepturi, illum quos!
                      </div>
                    </div>
                  </article>
                </div>
              </section> */}
            </>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;